name: Update VPNGate Servers

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-servers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Fetch Script (VPNGate)
      run: python fetch_vpngate.py

    - name: Commit and Push if updated
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add servers.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update top VPNGate servers" && git push)
